diploiTemplateVersion: V1.0
name: diploi-odoo
description: Odoo ERP template
defaultName: Odoo

stages:
  - name: Development
    identifier: development
  - name: Staging
    identifier: staging
  - name: Production
    identifier: production

contexts:
  - name: odoo
    identifier: odoo
  - name: postgres
    identifier: postgres

parameterGroups:
  - name: PostgreSQL Database
    identifier: postgres
    toggleable: true
    description: Database connection info
    defaultValue: TRUE
    parameters:
      - name: Host
        identifier: POSTGRES_HOST
        defaultValue: postgres
        type: string
      - name: Port
        identifier: POSTGRES_PORT
        defaultValue: 5432
        type: integer
      - name: User
        identifier: POSTGRES_USER
        defaultValue: odoo
        type: string
        contexts: label=postgres,label=odoo
      - name: Password
        identifier: POSTGRES_PASSWORD
        defaultValue: postgresodoo
        type: secret
      - name: Schema
        identifier: POSTGRES_DB
        defaultValue: odoo
        type: string

environmentVariables:
  - identifier: TEST
    defaultValue: This text comes from an environment variable
    type: string
    contexts: label=odoo

repositories:
  - name: odoo
    identifier: odoo

hosts:
  - name: Odoo
    identifier: odoo
    urlFormat: '[label].[default-domain]'

ssh:
  - usernameFormat: '[label]'
    contexts: label=odoo
    containerUser: odoo
    editorPath: /mnt/extra-addons
    stages:
      - development
  - usernameFormat: '[label]-root'
    contexts: label=odoo
    containerUser: root
    editorPath: /root
    stages:
      - development
  - usernameFormat: '[label]-[index]'
    contexts: label=odoo
    containerUser: odoo
    stages:
      - production
  - usernameFormat: '[label]-[index]-root'
    contexts: label=odoo
    containerUser: root
    stages:
      - production
  - usernameFormat: '[label]-postgres'
    contexts: label=postgres

logs:
  - identifier: odoo-log
    name: Odoo Log
    labelSelector: app=odoo
    command: tail -n 2000 -F /var/log/odoo.log

actions:
  - identifier: odoo-restart
    name: Restart Odoo
    labelSelector: app=odoo
    command: supervisord restart odoo

images:
  - identifier: odoo
    repository: odoo
    dockerfile: Dockerfile
    image: ghcr.io/diploi/odoo-template
    stages:
      - development
      - production
      - staging
    manualBuildStages:
      - development

storage:
  # /var/lib/odoo
  - identifier: odoo
    stages:
      - production
      - staging
      - development
    sizeMb: 8000
  - identifier: development
    stages:
      - development
    sizeMb: 8000
  - identifier: postgres
    stages:
      - production
      - staging
      - development
    sizeMb: 10000

status:
  url: http://odoo:3000/status
