apiVersion: apps/v1
{{- if eq .Values.stage "development"}}
kind: StatefulSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: odoo
  labels:
    app: odoo
spec:
  selector:
    matchLabels:
      app: odoo
  {{- if eq .Values.stage "development"}}
  serviceName: odoo
  {{- else }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  {{- end }}
  replicas: {{ ternary 1 0 .Values.enabled }}
  template:
    metadata:
      labels:
        app: odoo
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: diploi-pull-secret
      containers:
        - name: odoo
          image: {{ .Values.images.odoo }}
          imagePullPolicy: Always
          #command: ['sh', '-c', 'echo The app is running! && sleep 10000']
          ports:
            - containerPort: 8069
            - containerPort: 3000
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/pod-ready
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            {{- range .Values.env }}
            {{- if contains "odoo" .contexts }}
            - name: {{ .identifier }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
            {{- range .Values.parameterGroups }}
            - name: {{ .identifier }}
              value: {{ .value | quote }}
            {{- end }}
            - name: REPOSITORY_URL
              value: {{ .Values.repositories.odoo.url }}
            - name: REPOSITORY_BRANCH
              value: {{ .Values.repositories.odoo.branch }}
            - name: APP_PUBLIC_URL
              value: {{ .Values.hosts.odoo }}
            - name: STAGE
              value: {{ .Values.stage }}
            - name: HOST
              value: {{ .Values.parameterGroupsMap.POSTGRES_HOST | quote }}
            - name: PORT
              value: {{ .Values.parameterGroupsMap.POSTGRES_PORT | quote }}
            - name: USER
              value: {{ .Values.parameterGroupsMap.POSTGRES_USER | quote }}
            - name: PASSWORD
              value: {{ .Values.parameterGroupsMap.POSTGRES_PASSWORD | quote }}
          volumeMounts:
            - name: data-mount
              mountPath: /var/lib/odoo
            {{- if hasKey .Values.storage "odoohome" }}
            - name: home-mount
              mountPath: /home/odoo
            {{- end }}
            {{- if hasKey .Values.storage "odooaddons" }}
            - name: addons-mount
              mountPath: /mnt/extra-addons
            {{- end }}
            - name: ssh-keys
              mountPath: /etc/ssh/internal_ssh_host_rsa.pub
              subPath: internal_ssh_host_rsa.pub
            - name: diploi-git
              mountPath: /etc/diploi-git
      volumes:
        - name: data-mount
          hostPath:
            path: {{ .Values.storage.odoodata.hostPath }}
        {{- if hasKey .Values.storage "odoohome" }}
        - name: home-mount
          hostPath:
            path: {{ .Values.storage.odoohome.hostPath }}
        {{- end }}
        {{- if hasKey .Values.storage "odooaddons" }}
        - name: addons-mount
          hostPath:
            path: {{ .Values.storage.odooaddons.hostPath }}
        {{- end }}
        - name: ssh-keys
          secret:
            secretName: ssh-keys
        - name: diploi-git
          secret:
            secretName: diploi-git



