apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - hosts:
        - {{ .Values.hosts.odoo }}
      secretName: tls-secret
  rules:
    - host: {{ .Values.hosts.odoo }}
      http:
        paths:
          - path: '/'
            pathType: Prefix
            backend:
              service:
                name: odoo
                port: 
                  number: 8069
