apiVersion: v1
kind: Service
metadata:
  name: odoo
spec:
  ports:
    - port: 80
      name: odoo
    - port: 3000
      name: status
  selector:
    app: {{ ternary "odoo" "disabled" .Values.enabled }}
