name: Odoo16ArmBuild

#
# Since Odoo doesnt' provide an Arm build we need to do one ourselves
# NOTE! This is triggered with odoo-v0.0.1 style tag so we don't always 
#       do this

on:
  push:
    tags:
      - 'odoo-*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: diploi/odoo16-arm

jobs:
  build:
    runs-on: buildjet-8vcpu-ubuntu-2204-arm
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the GitHub container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:Odoo16Docker"
          file: Dockerfile
          platforms: linux/arm64
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}